<?php
// CON ESTE SCRIPT DEBEMOS MOSTRAR LAS OPERACIONES DE DEVOLUCION QUE NO RETORNAN
/*
    1. CONSULTAMOS EN LA TABLA "operacion_devolucion" AQUELLAS QUE SEAN DE NO RETORNO
    2. DEBEMOS TRAER SU DETALLE DE OPERACIONES DE DEVOLUCION DE CALIDAD "operacion_devolucion_calidad"
*/