<?php
// EN ESTE SCRIPT DEBE ESTAR LA OPERACION DE REGISTRO
// TIPO: INTEGRACION
/*
    1. EN EL SISTEMA EMAFACT SE REALIZA UNA OPERACION DE NOTA DE CREDITO
    2. AQUELLAS QUE SON DEL TIPO DE MOTIVO CORRESPONDIENTE SON DE NUESTRO INTERES
    (devolucion total, anulacion de pedido, devolucion parcial)
    3. SE COMUNICA CON EL SISTEMA EMAPROD Y CREA EL REGISTRO CORRESPONDIENTE
*/